import com.garmin.fit.GarminProduct;

public class FitTools {
    public static String productById(int garminProduct) {
        switch (garminProduct) {
            case GarminProduct.HRM1:    return "HRM1";
            case GarminProduct.ALF04:   return "ALF04";
            case GarminProduct.AMX:     return "AMX";
            case GarminProduct.ANDROID_ANTPLUS_PLUGIN:  return "Android ANT+ Plugin";
            case GarminProduct.AXB01:   return "AXB01";
            case GarminProduct.AXB02:   return "AXB02";
            case GarminProduct.AXH01:   return "AXH01 HRM chipset";
            case GarminProduct.BCM:     return "BCM model for ANT+";
            case GarminProduct.BSM:     return "BSM model for ANT+";
            case GarminProduct.CHIRP:   return "CHIRP";
            case GarminProduct.CONNECT: return "сайт Garmin Connect";
            case GarminProduct.DSI_ALF01:   return "DSI_ALF01";
            case GarminProduct.DSI_ALF02:   return "DSI_ALF02";
            case GarminProduct.EDGE1000:    return "Edge 1000";
            case GarminProduct.EDGE200:     return "Edge 200";
            case GarminProduct.EDGE200_TAIWAN:  return "Edge 200 (Тайвань)";
            case GarminProduct.EDGE500:     return "Edge 500";
            case GarminProduct.EDGE500_CHINA:   return "Edge 500 (Китай)";
            case GarminProduct.EDGE500_JAPAN:   return "Edge 500 (Япония)";
            case GarminProduct.EDGE500_KOREA:   return "Edge 500 (Корея)";
            case GarminProduct.EDGE500_TAIWAN:  return "Edge 500 (Тайвань)";
            case GarminProduct.EDGE510:     return "Edge 510";
            case GarminProduct.EDGE510_ASIA:    return "Edge 510 (Азия)";
            case GarminProduct.EDGE510_JAPAN:   return "Edge 510 (Япония)";
            case GarminProduct.EDGE510_KOREA:   return "Edge 510 (Корея)";
            case GarminProduct.EDGE800:     return "Edge 800";
            case GarminProduct.EDGE800_CHINA:   return "Edge 800 (Китай)";
            case GarminProduct.EDGE800_JAPAN:   return "Edge 800 (Япония)";
            case GarminProduct.EDGE800_KOREA:   return "Edge 800 (Корея)";
            case GarminProduct.EDGE800_TAIWAN:  return "Edge 800 (Тайвань)";
            case GarminProduct.EDGE810:     return "Edge 810";
            case GarminProduct.EDGE810_CHINA:   return "Edge 810 (Китай)";
            case GarminProduct.EDGE810_JAPAN:   return "Edge 810 (Япония)";
            case GarminProduct.EDGE810_TAIWAN:  return "Edge 810 (Тайвань)";
            case GarminProduct.EDGE_REMOTE:     return "Edge Remote";
            case GarminProduct.EDGE_TOURING:    return "Edge Touring/Touring+";
            case GarminProduct.EPIX:    return "Epix";
            case GarminProduct.FENIX:   return "Fenix";
            case GarminProduct.FENIX2:  return "Fenix2";
            case GarminProduct.FR10:    return "Forerunner 10";
            case GarminProduct.FR10_JAPAN:  return "Forerunner 10 (Япония)";
            case GarminProduct.FR110:   return "Forerunner 110";
            case GarminProduct.FR110_JAPAN: return "Forerunner 110 (Япония)";
            case GarminProduct.FR15:    return "Forerunner 10";
            case GarminProduct.FR210_JAPAN: return "Forerunner 210 (Япония)";
            case GarminProduct.FR220:   return "Forerunner 220";
            case GarminProduct.FR220_CHINA: return "Forerunner 220 (Китай)";
            case GarminProduct.FR220_JAPAN: return "Forerunner 220 (Япония)";
            case GarminProduct.FR301_CHINA: return "Forerunner 301 (Китай)";
            case GarminProduct.FR301_JAPAN: return "Forerunner 301 (Япония)";
            case GarminProduct.FR301_KOREA: return "Forerunner 301 (Корея)";
            case GarminProduct.FR301_TAIWAN:    return "Forerunner 301 (Тайвань)";
            case GarminProduct.FR310XT:     return "Forerunner 310XT";
            case GarminProduct.FR310XT_4T:  return "Forerunner 310XT-4T";
            case GarminProduct.FR405:       return "Forerunner 405";
            case GarminProduct.FR405_JAPAN: return "Forerunner 405 (Япония)";
            case GarminProduct.FR50:        return "Forerunner 50";
            case GarminProduct.FR60:        return "Forerunner 60";
            case GarminProduct.FR610:       return "Forerunner 610";
            case GarminProduct.FR610_JAPAN: return "Forerunner 610 (Япония)";
            case GarminProduct.FR620:       return "Forerunner 620";
            case GarminProduct.FR620_CHINA: return "Forerunner 620 (Китай)";
            case GarminProduct.FR620_JAPAN: return "Forerunner 620 (Япония)";
            case GarminProduct.FR70:        return "Forerunner 60";
            case GarminProduct.FR910XT:     return "Forerunner 910XT";
            case GarminProduct.FR910XT_CHINA:   return "Forerunner 910XT (Китай)";
            case GarminProduct.FR910XT_JAPAN:   return "Forerunner 910XT (Япония)";
            case GarminProduct.FR910XT_KOREA:   return "Forerunner 910XT (Корея)";
            case GarminProduct.FR920XT:     return "Forerunner 910XT";
            case GarminProduct.HRM2SS:  return "HRM 2 Soft Strap";
            case GarminProduct.HRM3SS:  return "HRM 3 Soft Strap";
            case GarminProduct.HRM_RUN: return "HRM Run";
            case GarminProduct.HRM_RUN_SINGLE_BYTE_PRODUCT_ID: return "HRM Run model for HRM ANT+";
            case GarminProduct.SDM4:    return "SDM4 датчик бега";
            case GarminProduct.SWIM:    return "Swim";
            case GarminProduct.TEMPE:   return "Tempe (датчик температуры)";
            case GarminProduct.TRAINING_CENTER: return "Training Center";
            case GarminProduct.VECTOR_CP:   return "Vector (контктные педали)";
            case GarminProduct.VECTOR_SS:   return "Vector (односторонний датчик)";
            case GarminProduct.VIRB_ELITE:  return "Virb Elite";
            case GarminProduct.VIRB_REMOTE: return "Virb Remote";
            case GarminProduct.VIVO_FIT:    return "Vivo Fit";
            case GarminProduct.VIVO_FIT2:   return "Vivo Fit2";
            case GarminProduct.VIVO_KI:     return "Vivo KI";
            case GarminProduct.VIVO_SMART:  return "Vivo Smart";
         }
        return "неизвестное устройство";
    }
}
